# 1. Numpy

* 수학, 과학 계산용 패키지
* 자료 구조 : ndarray, 파이썬의 list보다 빠름, 적은 메모리를 사용


In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy

In [3]:
numpy

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

### 1-1. ndarray

In [6]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

print(list1)
print(list2)

print(type(list1))
print(type(list2))

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'list'>


In [7]:
ndarr1 = np.array([1, 2, 3, 4])

print(ndarr1)
print(type(ndarr1)) # numpy.ndarray = n dimension array

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
# 리스트를 ndarray로 변환하는 방법

ndarr1 = np.array(list1)
ndarr2 = np.array(list2)

print(ndarr1)
print(type(ndarr1))
print(ndarr2)
print(type(ndarr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


### 1-2. ndarray의  data type

* ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [9]:
list1 = [1, 3.14, 'python', True]

In [10]:
list1

[1, 3.14, 'python', True]

In [11]:
list1[3]

True

In [12]:
ndarr1 = np.array([1, 2, 3, 4])

In [13]:
ndarr1

array([1, 2, 3, 4])

In [14]:
ndarr2 = np.array([1, 2, 3, 3.14, 4])

In [15]:
ndarr2

array([1.  , 2.  , 3.  , 3.14, 4.  ])

In [16]:
ndarr3 = np.array([1, 2, 3, 3.14, True])

In [17]:
ndarr3

array([1.  , 2.  , 3.  , 3.14, 1.  ])

In [18]:
bool(10)

True

In [19]:
bool('python')

True

In [20]:
bool(0)

False

In [21]:
bool('')

False

In [22]:
bool(None)

False

In [23]:
ndarr5 = np.array([1, 2, 3, 3.14, True, '1234'], dtype=int)
ndarr5

array([   1,    2,    3,    3,    1, 1234])

In [24]:
ndarr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
ndarr2d.shape

(3, 4)

In [25]:
print(ndarr2d[0, 2])
print(ndarr2d[0][2])
print(ndarr2d[2, 1])

3
3
10


In [26]:
# 0행을 가져오기

print(ndarr2d[0])
print(ndarr2d[0,])
print(ndarr2d[0, :])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [27]:
# 0열을 가져오기

print(ndarr2d[:, 0])

[1 5 9]


In [28]:
print(ndarr2d[:2, :])
print(ndarr2d[:2, 2:])

[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]


In [29]:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

### 1-4. Fancy 인덱싱

* 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [30]:
ndarr1 = np.array([10, 23, 2, 6, 90, 85, 32, 66, 80])

In [31]:
idx = [1, 4, 6]

In [32]:
ndarr1[idx]

array([23, 90, 32])

In [33]:
ndarr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [34]:
ndarr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1-5. Boolean 인덱싱

* 조건 필터링을 통하여 Boolean 값을 이용한 색인

In [35]:
ndarr1 = np.array(['^^'])

#2. 행렬 연산

##2-1. 연산자

In [36]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [37]:
# 덧셈 연산
# shape가 같아야 함
# 같은 position 끼리 연산

a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [38]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4],
              [1, 2]])

In [39]:
# a + b ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [40]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [41]:
# 뺄셈 연산
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [42]:
# 곱셈 연산
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [43]:
# 나눗셈 연산
a / b

array([[0.33333333, 0.5       , 0.6       ],
       [2.        , 1.5       , 1.33333333]])

In [45]:
# dot product(행렬의 내적)
# 맞닿는 shape가 같아야 함
# 떨어져 있는 shape가 결과 행렬이 됌

a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [46]:
a.shape, b.shape

((3, 3), (3, 2))

In [47]:
print((1*1+2*3+3*5), (1*2+2*4+3*6))
print((1*1+2*3+3*5), (1*2+2*4+3*6))
print((2*1+3*3+4*5), (2*2+3*4+4*6))

22 28
22 28
31 40


In [48]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

##2-2. arange

* 순차적인 값을 생성할 때 사용

In [49]:
arr1 = range(1, 11)

In [50]:
arr1

range(1, 11)

In [51]:
for i in arr1:
  print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 

In [52]:
arr2 = np.arange(1, 11)

In [53]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
for i in arr2:
  print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 

##2-3. sort

In [55]:
li = [3, 5, 7, 1, 2]

In [56]:
li = sorted(li)
print(li)

[1, 2, 3, 5, 7]


In [57]:
li.sort()

In [58]:
li

[1, 2, 3, 5, 7]

In [60]:
ndarr1 = np.array([1, 10, 5, 7, 2, 4, 3, 6, 8, 9])
ndarr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [61]:
np.sort(ndarr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
ndarr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [63]:
np.sort(ndarr1)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [66]:
# 문자열 역순으로 출력하기

s = 'python'
print(s[::-1])
print(s[3:0:-1]) # 3번 인덱스부터 0직전 까지 역순으로 1개씩 가져오기
print(s[3::-1]) # 3번 인덱스부터 0까지 역순으로 1개씩 가져오기
print(s[::-1]) # 마지막부터 0까지 역순으로 1개씩 가져오기

nohtyp
hty
htyp
nohtyp


In [68]:
ndarr2d = np.array([[11, 10, 12, 9],
                    [3, 1, 4 ,2],
                    [5, 6, 7, 8]])

In [69]:
ndarr2d.shape

(3, 4)

In [70]:
# 행 정렬

np.sort(ndarr2d, axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [71]:
# 열 정렬

np.sort(ndarr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [72]:
# 축의 마지막 방향

np.sort(ndarr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

##2-4. 숫자의 단일 연산

In [74]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[3, 3, 3], [3, 3, 3]])

In [75]:
a + b

array([[4, 5, 6],
       [7, 8, 9]])

In [79]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [76]:
a - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [77]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [78]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])